api:
  env: SIT

spring:
  datasource:
    username: SIT-DB-username
    password: SIT-DB-password
    url: jdbc:postgresql://localhost:5432/schema_sit

  jpa:
    show-sql: true
    generate-ddl: true

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        show_sql: true