api:
  env: DEV
server:
  port: 9091

spring:
  datasource:
    username: DEV-DB-username
    password: DEV-DB-password
    url: jdbc:postgresql://localhost:5432/schema_dev

  jpa:
    show-sql: true
    generate-ddl: true

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        show_sql: true