---
- hosts: webservers
  vars:
    app_name: 'Ansible POC App'
    app_version: 1.0.0
    app_jar: spring-ansible-0.0.1-SNAPSHOT.jar
    app_source_dir: ../build/libs
    app_deploy_dir: /home/thiago
  connection: local
  tasks:
    - name: Copy JAR file
      copy:
        src: "{{ app_source_dir }}/{{ app_jar }}"
        dest: "{{ app_deploy_dir }}/{{ app_jar }}"
        remote_src: yes