---
- hosts: webservers
  become: true
  vars:
    app_name: 'Ansible POC App'
    app_version: 1.0.0
    username: thiago
    app_source_dir: ../build/libs
    app_deploy_dir: /home/{{ username }}
  connection: local
  tasks:
    - name: Copy JAR file
      copy:
        src: "{{ app_source_dir }}/{{ app_jar }}"
        dest: "{{ app_deploy_dir }}/{{ app_jar }}"
        remote_src: yes