---
- hosts: webservers
  vars:
    springboot_application_name: 'application name'
  connection: local
  tasks:
    - name: Run jar
      shell: nohup java -jar ../build/libs/spring-ansible-0.0.1-SNAPSHOT.jar &
      async: 15
      poll: 5