---
- hosts: webservers
  connection: local
  vars:
    springboot_application_name: 'application name'
  tasks:
#    - name: Copy the jar file
#      copy:
#        src: ../build/libs/spring-ansible-0.0.1-SNAPSHOT.jar
#        dest:  $HOME/app
    - name: Run jar
      shell: java -jar ../build/libs/spring-ansible-0.0.1-SNAPSHOT.jar